package com.csye6225.assignment1.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Announcements")
public class AnnouncementModel {

    private String id;
    private String announcementId;
    private String announcementText;
    private String boardId;

    public AnnouncementModel() {

    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexRangeKey(attributeName="announcementId", globalSecondaryIndexName = "boardId-announcementId-index")
    public String getAnnouncementId() {
        return announcementId;
    }

    public void setAnnouncementId(String announcementId) {
        this.announcementId = announcementId;
    }

    @DynamoDBAttribute(attributeName="announcementText")
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBIndexHashKey(attributeName="boardId", globalSecondaryIndexName = "boardId-announcementId-index")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }
}
