package com.csye6225.assignment1.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Registrar")
public class RegistrarModel {

    private String id;
    private String registrationId;
    private String offeringId;
    private String offeringType;
    private String department;
    private int perUnitPrice;

    public RegistrarModel() {}

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String Id) {
        this.id = Id;
    }

    @DynamoDBAttribute(attributeName = "RegistrationId")
    public String getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }


    @DynamoDBAttribute(attributeName = "OfferingId")
    public String getOfferingId() {
        return offeringId;
    }

    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId;
    }


    @DynamoDBAttribute(attributeName = "OfferingType")
    public String getOfferingType() {
        return offeringType;
    }

    public void setOfferingType(String offeringType) {
        this.offeringType = offeringType;
    }


    @DynamoDBAttribute(attributeName = "Department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }


    @DynamoDBAttribute(attributeName = "PerUnitPrice")
    public int getPerUnitPrice() {
        return perUnitPrice;
    }

    public void setPerUnitPrice(int perUnitPrice) {
        this.perUnitPrice = perUnitPrice;
    }
}
